{
  "errors": [
    {
      "message": "@unique is not permitted on Timestamp fields",
      "hint": "",
      "code": "TypeError",
      "pos": {
        "filename": "testdata/validation_unique_restrictions/schema.keel",
        "offset": 213,
        "line": 13,
        "column": 30
      },
      "endPos": {
        "filename": "testdata/validation_unique_restrictions/schema.keel",
        "offset": 220,
        "line": 13,
        "column": 37
      }
    },
    {
      "message": "Cannot use @unique on a repeated model field",
      "hint": "In a one to one relationship, there are no repeated fields. To learn more about relationships, visit https://docs.keel.so/models#relationships",
      "code": "RelationshipError",
      "pos": {
        "filename": "testdata/validation_unique_restrictions/schema.keel",
        "offset": 264,
        "line": 15,
        "column": 9
      },
      "endPos": {
        "filename": "testdata/validation_unique_restrictions/schema.keel",
        "offset": 269,
        "line": 15,
        "column": 14
      }
    },
    {
      "message": "@unique is not permitted on has many relationships",
      "hint": "",
      "code": "TypeError",
      "pos": {
        "filename": "testdata/validation_unique_restrictions/schema.keel",
        "offset": 277,
        "line": 15,
        "column": 22
      },
      "endPos": {
        "filename": "testdata/validation_unique_restrictions/schema.keel",
        "offset": 284,
        "line": 15,
        "column": 29
      }
    },
    {
      "message": "@unique is not permitted on has many relationships",
      "hint": "",
      "code": "TypeError",
      "pos": {
        "filename": "testdata/validation_unique_restrictions/schema.keel",
        "offset": 362,
        "line": 19,
        "column": 20
      },
      "endPos": {
        "filename": "testdata/validation_unique_restrictions/schema.keel",
        "offset": 367,
        "line": 19,
        "column": 25
      }
    },
    {
      "message": "Field 'name' has already been specified as a constraint",
      "hint": "",
      "code": "TypeError",
      "pos": {
        "filename": "testdata/validation_unique_restrictions/schema.keel",
        "offset": 438,
        "line": 22,
        "column": 20
      },
      "endPos": {
        "filename": "testdata/validation_unique_restrictions/schema.keel",
        "offset": 442,
        "line": 22,
        "column": 24
      }
    },
    {
      "message": "Field 'name' has already been specified as a constraint",
      "hint": "",
      "code": "TypeError",
      "pos": {
        "filename": "testdata/validation_unique_restrictions/schema.keel",
        "offset": 498,
        "line": 25,
        "column": 34
      },
      "endPos": {
        "filename": "testdata/validation_unique_restrictions/schema.keel",
        "offset": 502,
        "line": 25,
        "column": 38
      }
    }
  ]
}