{
  "errors": [
    {
      "message": "The model 'Person' cannot have a field of its own type unless it is optional.",
      "hint": "",
      "code": "TypeError",
      "pos": {
        "filename": "testdata/validation_field_required_of_same_model_type/schema.keel",
        "offset": 43,
        "line": 3,
        "column": 16
      },
      "endPos": {
        "filename": "testdata/validation_field_required_of_same_model_type/schema.keel",
        "offset": 49,
        "line": 3,
        "column": 22
      }
    }
  ]
}